DROP USER sprout;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
show con_name;

CREATE USER sprout IDENTIFIED BY sprout
    DEFAULT TABLESPACE Users 
    QUOTA UNLIMITED ON Users;

GRANT CONNECT TO sprout;
GRANT CREATE TABLE TO sprout;
GRANT CREATE SEQUENCE TO sprout;
GRANT CREATE VIEW TO sprout;
GRANT CREATE INDEXTYPE TO sprout;
GRANT CREATE PROCEDURE TO sprout;
GRANT CREATE TRIGGER TO sprout;
GRANT CREATE SESSION TO sprout;
GRANT CREATE JOB TO sprout;
GRANT EXECUTE ON sys.dbms_crypto TO sprout;
GRANT sysdba TO sprout;
COMMIT;
